apiVersion: v1
kind: Service
metadata:
  labels:
    app: lxcfs-demo
  name: lxcfs-demo-svc
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: lxcfs-demo
  sessionAffinity: None
  type: ClusterIP
